<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Zend Framework Application</title>
        <?php echo $this->headLink()->appendStylesheet('/styles/common.css') ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('/scripts/jquery-1.11.3.min.js')) ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('/scripts/common.js')) ?>
    </head>
    <body>
        <div id="header" style="background-color: #EEEEEE; height: 30px;">

        </div>

        <?php echo $this->layout()->content; ?>

    </body>
</html>
